### ISSUE TITLE
Gulp looks for .less instead .scss

### ISSUE THREAD

**Issue by DennisKo** [roots/sage#1648]
When running gulp on a fresh install of the most current Sage I get:

[08:55:20] Starting 'styles'...
'layouts/tinymce.less' wasn't found. Tried - C:\xampp\htdocs\kt-mai\wp-content\themes\sage-master\assets\styles\layouts\tinymce.less,layouts\tinymce.less in file C:\xampp\htdocs\kt-mai\wp-content\themes\sage-master\assets\styles\main.scss line no. 19

node 6.1.0
gulp 3.9.1
windows 10

**Comment by adriandmitroca** [comment]
+1

This bug started after update to Node 6.x.

**Comment by DennisKo** [comment]
Fixed with a downgrade to Node v4.4.4!

**Comment by adriandmitroca** [comment]
Downgrade isn't really a fix.

**Comment by joshmanders** [comment]
The issue is because https://github.com/roots/sage/blob/master/gulpfile.js#L89 `gulpif` needs a boolean value here. Passing a string is a truthy value, therefore it's passing it off the `less()` to do and then piping down to `sass()` which then is using yet another truthy string value so the less files are trying to be ran through sass.

**Comment by joshmanders** [comment]
Upgrade `gulp-if` to latest version should fix it.

**Comment by SkullMasher** [comment]
@joshmanders Thanks for the suggestion running ncu -a returned the following.
```
 del                 ^1.2.1  →  ^2.2.0 
 gulp-autoprefixer   ^2.3.1  →  ^3.1.0 
 gulp-flatten         0.1.1  →   0.2.0 
 gulp-if             ^1.2.5  →  ^2.0.1 
 gulp-imagemin       ^2.3.0  →  ^3.0.1 
 gulp-jshint        ^1.11.2  →  ^2.0.1 
 gulp-rev            ^6.0.0  →  ^7.0.0 
 wiredep             ^2.2.2  →  ^4.0.0 
```
After the upgrade the message still appears. scss can't compile.

Running node v6.1.0 on Debian if that matters...

**Comment by SkullMasher** [comment]
I commented those line on yourawesometheme/gulpfile.js (line 88 to 90)
```
.pipe(function() {
  return gulpif('*.less', less());
})
```
To continue working on my project since I don't use less.

**Comment by nmfzone** [comment]
It still exists until now, maybe because sage repo in composer still not include that fix "Update gulp-if". So, when the version (after that fix) comes up to sage repo in composer?

**Comment by samkarpluk** [comment]
I set up the roots-example-project yesterday and got this error when I ran gulp. Commenting out lines 88-90 made the error go away.

Node: 6.3.0
Gulp: 3.9.1

**Comment by jasperf** [comment]
Still an issue. see https://discourse.roots.io/t/compiling-new-scss-error-less-not-found/7312/5 where I talked about it.

**Comment by ciromattia** [comment]
Nope, you have to update `gulp-if` (see 2d3f25b above)

**Comment by nmfzone** [comment]
@ciromattia I think everyone knows that. But the problem is sage repo in composer still not include that fix "Update gulp-if". So, i think everyone who doesn't know this issue (or maybe new user) still face the error.

**Comment by simonh1000** [comment]
So, I have just ran into this error the first time I tried to recompile my installation post-upgrading to Node 6.x. I'm not at all clear from the above what to do, and simply upgrading gulp-if just led to a different error `throw new TypeError('Path must be a string. Received ' + inspect(path));`. If I upgrade to the latest Sage, will it work again - @nmfzone seems to be suggesting not?

**Comment by nmfzone** [comment]
@simonh1000 I think your problem doesn't fully relate to this issue, because you still use the older version of Sage. At least use version 8.4.2, then update your gulp-if to 2.0.1. Hope that helps.

**Comment by rossyoung5** [comment]
I am still running into this issue. I've updated gulp-if and commented out lines 88-90 in gulpfile.js. When I run gulp it just hangs on styles:
~~~~
[15:42:19] Using gulpfile /Applications/MAMP/htdocs/dnortho/wp-content/themes/dnortho/gulpfile.js
[15:42:19] Starting 'clean'...
[15:42:19] Finished 'clean' after 3.81 ms
[15:42:19] Starting 'default'...
[15:42:19] Starting 'build'...
[15:42:19] Starting 'wiredep'...
[15:42:19] Finished 'default' after 197 ms
[15:42:19] Finished 'wiredep' after 222 ms
[15:42:19] Starting 'styles'...
~~~~

I've uninstalled node, npm, bower, gulp; kinda at a loss as to why it's getting stuck here. Any thoughts?

**Comment by rossyoung5** [comment]
Oh also using node 4.4.4, sage 8.4.2, gulp 3.9.1

**Comment by thisolivier** [comment]
@rossyoung5 I think that's a different issue, node 4.4.4 shouldn't be affected, indeed downgrading was an early solution to the problem. Gulp can hang on styles for a number of reasons, are you sure it's related to gulp looking for .less files?

**Comment by rossyoung5** [comment]
@thisolivier At one point I had the same error as @DennisKo, and after downgrading node it went back to hanging up on styles. I think it's related somehow, but I am having trouble identifying the cause. My coworker is using the same sage project and can gulp with no issues. I've made sure we're using the same versions of all build tools. You said there are a number of reasons it might be hanging up, I'd love to hear any you'd be willing to share. Thanks!

**Comment by thisolivier** [comment]
I'd be happy to, but I don't think this is the right thread to work on it (especially if your colleague has the same setup and is able to gulp without issues). If you create a topic in the roots discourse I'd be happy to contribute.

**Comment by rossyoung5** [comment]
@thisolivier Great will do, thanks.

**Comment by rossyoung5** [comment]
@thisolivier https://discourse.roots.io/t/gulp-hanging-up-on-styles-during-compile-and-wont-complete/7832

**Comment by CatinhoCR** [comment]
I am also getting this error. 
Using sage 8.4.2 on an old client's website, with node 7.4.0 and gulp-if 4.0.5.
Been playing with the node versions a lot lately and everytime I switch to this old versions of sage I need to run a npm rebuild node-sass somewhy, probably not related tough.

Commenting the lines gulpfile from 88 to 90 fixed the compilation issue for now, a temporary fix that worked but would like to get more light into what might be wrong.

**Comment by emieldesmidt** [comment]
If you don't want to downgrade node, or avoid using less, you can do the following fix that I've found on another blog: In the gulpfile.js file you change the order of the lines regarding *.scss and *.less. It should look like this:
` .pipe(function() {
      return gulpif('*.scss', sass({
        outputStyle: 'nested', // libsass doesn't support expanded yet
        precision: 10,
        includePaths: ['.'],
        errLogToConsole: !enabled.failStyleTask
      }));
    })
    .pipe(function() {
      return gulpif('*.less', less());
    })`

credits go to MariamLachhab at https://discourse.roots.io/t/layouts-tinymce-less-wasnt-found/6645/5

**Comment by aaegorof** [comment]
The best workaround that i found was very SIMPLE !
Just add to your manifest the main.less file... Like so:
    ```
"main.css": {
      "files": [
        "styles/main.less",
        "styles/main.scss"
      ],
      "main": true
    }
```
That will COMBINE together less and SASs
