### ISSUE TITLE
When running `npm start`  `*.scss` or `*.css` file changes cause browser-sync to reloads the page instead of injecting the css changes.

### ISSUE THREAD

**Issue by geschwendt** [roots/sage#1713]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [X] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

When running `npm start` any asset change (css, js, scss) results in a browser-sync full page refresh.

**What is the expected or desired behavior?**

When running `npm start` any css/scss changes should be injected instead of a full page refresh.

---

This stopped working in version 9.0.0-alpha.2 when the `npm watch` workflow was removed.

**Comment by derkjn** [comment]
I guess this is not really a bug, just a different configuration, since the `webpack-dev-server` is not listed in the given `package.json` file.
I'm not too sure though if the current version of the dev-server is compatible with webpack2.

**Comment by geschwendt** [comment]
I have the HMR working with the older implementation using`webpack-dev-middleware` and `webpack-hot-middleware` as browser-sync middleware & works with the newer build refactor. 

I guess I'm wondering why the HMR feature was removed?

**Comment by QWp6t** [comment]
It wasn't deliberate. I thought I had tested it out with the webpack browsersync plugin and determined that the plugin was injecting the changes without reloading, effectively doing the same thing that we were doing in alpha 1. But I must've had some wires crossed or something since obviously that's not the case.

I'll get this fixed before the next alpha release.

**Comment by QWp6t** [comment]
This fixed in the master branch. New alpha version will be tagged soon.

**Comment by dani-z** [comment]
Hi all,

Don't want to open a new Issue but I'm still having the same problem after merging the master in my setup. The problem is like @geschwendt said. It opens the page with BS connected, it's rebuilding when I save a CSS or JS file but it does not inject the code in page.

I've also tried to add 
```
"watch": [
...
    "assets/**/*.scss"
...
  ],
```

The page is refreshed but again no css/js is injected. Will keep posting if I find anything on this.

Cheers

**Comment by dani-z** [comment]
@QWp6t any thoughts on this? I can't really manage to find the issue. Thanks

**Comment by Greg36** [comment]
@geschwendt I had a similar issue where HMR was connected and was injecting changes but with each change the browser was reloading as well. 

By default, BrowserSync is injecting changes only when css or image file changes. With php, html and js files it triggers a full page reload.

To change that just add [here](https://github.com/roots/sage/blob/master/assets/build/webpack.plugin.browsersync.js#L44) this: 
`injectFileTypes: ['scss','js'],`
