### ISSUE TITLE
MIME type (‘text/html’) not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by E-VANCE** [roots/sage#2054]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

Just ran into the same issue as described by _craigpearson_ [in this thread](https://discourse.roots.io/t/mime-type-text-html-not-a-supported-stylesheet-mime-type/11636/) and since there is no open (or closed) issue I wanted to bring this to attention...

Running Chrome 65.0.3325.181 on a Mac OS 10.11.6.

![bildschirmfoto 2018-04-09 um 16 39 12](https://user-images.githubusercontent.com/4123541/38504333-b2a3e26e-3c14-11e8-890d-5e1705a52b42.png)

[MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options#directives)

**Comment by Log1x** [comment]
This is related to #1989 (the MIME type returns `text/html` because it's the 404 page..)

This is resolved in Sage 10 as Mix builds the assets prior to starting Browsersync session.

**Comment by gbwashleybrown** [comment]
> This is related to #1989 (the MIME type returns `text/html` because it's the 404 page..)
> 
> This is resolved in Sage 10 as Mix builds the assets prior to starting Browsersync session.

Thats great, but this doesn't fix the problem in previous versions of the theme

**Comment by garrettw** [comment]
That is correct. So consider this a "wontfix".
